version: "3"
services:
  back:
    build: ./coligio-back
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./coligio-back:/app:cached
      - /app/node_modules
    environment:
      PORT: 80
      DB_DIALECT: mysql
      DB_PORT: 3306
      DB_HOST: db
      DB_NAME: $DB_NOME
      DB_USERNAME: $DB_USUARIO
      DB_PASSWORD: $DB_USUARIO_SENHA

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_SENHA
      MYSQL_USER: $DB_USUARIO
      MYSQL_PASSWORD: $DB_USUARIO_SENHA
      MYSQL_DATABASE: $DB_NOME
    volumes:
      - ./volumes/database:/var/lib/mysql

  front:
    build: ./coligio-front
    restart: unless-stopped
    volumes:
      - ./coligio-front:/app:cached
      - /app/node_modules
    environment:
      REACT_APP_API_URL: "//api.${BASE_URL}"
      PORT: 80
      CI: "true"

  nginx:
    image: nginx:1.13.3
    restart: unless-stopped
    depends_on:
      - back
      - front
    ports:
      - ${APP_PORT}:80
    environment:
      BASE_URL: $BASE_URL
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./config/nginx/run.sh:/run.sh
    command: /bin/bash -c "/run.sh"

