version: '3.7'

services:
  back:
    command: ['npm', 'run', 'production']

  front:
    command: ["npm", "run", "build"]
    volumes:
      - ./volumes/front/build:/app/build
    environment:
      CI: "false"

  nginx:
    volumes:
      - ./volumes/front/build:/www/coligio/build
      - ./config/nginx/nginx.conf.staging:/etc/nginx/nginx.conf.template
